"""cab_db add disc

Revision ID: 61c81e6d35f5
Revises: ea951731e4e3
Create Date: 2019-06-30 17:54:14.163995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c81e6d35f5'
down_revision = 'ea951731e4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_car_info', sa.Column('disc', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cab_car_info', 'disc')
    # ### end Alembic commands ###
