"""alter order_tab

Revision ID: 7bc959eb3d93
Revises: 61c81e6d35f5
Create Date: 2019-07-02 00:16:25.289739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc959eb3d93'
down_revision = '61c81e6d35f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_order_info', sa.Column('duration', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cab_order_info', 'duration')
    # ### end Alembic commands ###
