"""cab_db alter mold

Revision ID: ea951731e4e3
Revises: 307a4d71b1ae
Create Date: 2019-06-30 17:15:07.069532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea951731e4e3'
down_revision = '307a4d71b1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_car_info', sa.Column('mold', sa.String(length=32), nullable=True))
    op.drop_column('cab_car_info', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_car_info', sa.Column('type', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('cab_car_info', 'mold')
    # ### end Alembic commands ###
